apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
  labels:   
    app: mongo
spec:
  storageClassName: standard
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi