apiVersion: v1
kind: Pod
metadata:
  name: webcolor-from-secret
  labels:
    app: web-color
spec:
    containers:
    - image: mmumshad/simple-webapp-color
      name: webcolor-webserver
      env:
      - name: APP_COLOR
        valueFrom: 
            secretKeyRef:
                name: web-color-secret
                key: app_color
      ports:
      - containerPort: 8080
        protocol: TCP
        
