apiVersion: v1
kind: Pod
metadata:
  name: webcolor-from-env
  labels:
    app: web-color
spec:
 containers:
 - image: mmumshad/simple-webapp-color
   name: webcolor-webserver
   env:
   - name: APP_COLOR
     value: "blue"
   ports:
   - containerPort: 8080
     protocol: TCP
